create extension if not exists "pgcrypto";
create table municipalities(id uuid primary key default gen_random_uuid(),name text not null,department text not null,country text not null default 'Colombia',is_active boolean not null default true,created_at timestamptz not null default now());
create table questions(id uuid primary key default gen_random_uuid(),municipality_id uuid references municipalities(id) on delete cascade,question_text text not null,option_a_text text not null,option_a_dimension text not null,option_b_text text not null,option_b_dimension text not null,option_c_text text not null,option_c_dimension text not null,option_d_text text not null,option_d_dimension text not null,is_active boolean not null default true,created_at timestamptz not null default now());
create table candidates(id uuid primary key default gen_random_uuid(),municipality_id uuid not null references municipalities(id) on delete cascade,name text not null,party text not null,photo_url text,plan_pdf_url text,summary text,is_active boolean not null default true,created_at timestamptz not null default now());
create table candidate_scores(id uuid primary key default gen_random_uuid(),candidate_id uuid not null references candidates(id) on delete cascade,seguridad numeric default 0,empleo_desarrollo_economico numeric default 0,salud numeric default 0,educacion numeric default 0,infraestructura_movilidad numeric default 0,medio_ambiente numeric default 0,transparencia_corrupcion numeric default 0,participacion_ciudadana numeric default 0,cultura_deporte numeric default 0,servicios_publicos numeric default 0,analysis_json jsonb default '{}'::jsonb,created_at timestamptz not null default now());
create table citizen_results(id uuid primary key default gen_random_uuid(),session_id text not null,municipality_id uuid references municipalities(id),scores jsonb not null,created_at timestamptz not null default now());
create index on municipalities(is_active);create index on questions(municipality_id,is_active);create index on candidates(municipality_id,is_active);create index on citizen_results(municipality_id,created_at);
alter table municipalities enable row level security;alter table questions enable row level security;alter table candidates enable row level security;alter table candidate_scores enable row level security;alter table citizen_results enable row level security;
create policy "public read active municipalities" on municipalities for select using(is_active=true);create policy "public read active questions" on questions for select using(is_active=true);create policy "public read active candidates" on candidates for select using(is_active=true);create policy "public read scores for active candidates" on candidate_scores for select using(exists(select 1 from candidates c where c.id=candidate_id and c.is_active));create policy "public insert anonymous results" on citizen_results for insert with check(true);
create policy "admins all municipalities" on municipalities for all to authenticated using(true) with check(true);create policy "admins all questions" on questions for all to authenticated using(true) with check(true);create policy "admins all candidates" on candidates for all to authenticated using(true) with check(true);create policy "admins all scores" on candidate_scores for all to authenticated using(true) with check(true);create policy "admins read results" on citizen_results for select to authenticated using(true);
insert into municipalities(name,department) values('La Dorada','Caldas');
with m as (select id from municipalities where name='La Dorada' limit 1) insert into questions(municipality_id,question_text,option_a_text,option_a_dimension,option_b_text,option_b_dimension,option_c_text,option_c_dimension,option_d_text,option_d_dimension) select id,'¿Qué prioridad local considera más urgente?','Mejorar seguridad barrial','seguridad','Impulsar empleo local','empleo_desarrollo_economico','Fortalecer puestos de salud','salud','Mejorar vías y transporte','infraestructura_movilidad' from m;
insert into questions(question_text,option_a_text,option_a_dimension,option_b_text,option_b_dimension,option_c_text,option_c_dimension,option_d_text,option_d_dimension) values
('¿Dónde debería enfocarse más la alcaldía?','Calidad educativa','educacion','Protección ambiental','medio_ambiente','Lucha anticorrupción','transparencia_corrupcion','Participación comunitaria','participacion_ciudadana'),
('¿Qué servicio impacta más su vida diaria?','Agua y aseo','servicios_publicos','Deporte y cultura','cultura_deporte','Seguridad ciudadana','seguridad','Emprendimiento','empleo_desarrollo_economico');
with m as (select id from municipalities where name='La Dorada' limit 1), c as (insert into candidates(municipality_id,name,party,summary) select id,'Candidata Ejemplo','Movimiento ciudadano','Plan con énfasis en salud, educación e infraestructura.' from m returning id) insert into candidate_scores(candidate_id,seguridad,empleo_desarrollo_economico,salud,educacion,infraestructura_movilidad,medio_ambiente,transparencia_corrupcion,participacion_ciudadana,cultura_deporte,servicios_publicos,analysis_json) select id,5,6,9,8,8,4,5,6,5,7,'{}'::jsonb from c;
insert into storage.buckets(id,name,public) values('government-plans','government-plans',true) on conflict(id) do nothing;
create policy "public read government plans" on storage.objects for select using(bucket_id='government-plans');create policy "authenticated upload government plans" on storage.objects for insert to authenticated with check(bucket_id='government-plans');
