'use client';
import { useEffect, useMemo, useState } from 'react';import { supabaseBrowser } from '@/lib/supabase';import { DIMENSION_LABELS, DIMENSIONS, Dimension, emptyScores } from '@/lib/dimensions';import { matchCitizenToCandidate, normalizeScores, ScoreMap } from '@/lib/matching';import type { Candidate, Municipality, Question } from '@/lib/types';
type Step='municipio'|'encuesta'|'resultados';
export default function Evaluacion(){const supabase=supabaseBrowser();const [municipios,setMunicipios]=useState<Municipality[]>([]);const [municipio,setMunicipio]=useState('');const [questions,setQuestions]=useState<Question[]>([]);const [idx,setIdx]=useState(0);const [raw,setRaw]=useState(emptyScores());const [profile,setProfile]=useState<ScoreMap|null>(null);const [cands,setCands]=useState<Candidate[]>([]);const [step,setStep]=useState<Step>('municipio');const sessionId=useMemo(()=>{if(typeof window==='undefined')return '';let s=localStorage.getItem('radar_session_id');if(!s){s=crypto.randomUUID();localStorage.setItem('radar_session_id',s)}return s},[]);
useEffect(()=>{supabase.from('municipalities').select('*').eq('is_active',true).order('name').then(({data})=>setMunicipios(data||[]))},[]);
async function start(){const {data}=await supabase.from('questions').select('*').eq('is_active',true).or(`municipality_id.is.null,municipality_id.eq.${municipio}`);setQuestions((data||[]).sort(()=>Math.random()-.5).slice(0,10));setStep('encuesta')}
async function answer(dim:Dimension){const next={...raw,[dim]:raw[dim]+1};setRaw(next);if(idx+1>=questions.length){const p=normalizeScores(next);setProfile(p);await supabase.from('citizen_results').insert({session_id:sessionId,municipality_id:municipio,scores:p});const {data}=await supabase.from('candidates').select('*,candidate_scores(*)').eq('municipality_id',municipio).eq('is_active',true);setCands(data||[]);setStep('resultados')}else{setRaw(next);setIdx(idx+1)}}
if(step==='municipio')return <div className="card max-w-xl"><h1 className="text-2xl font-bold">Selecciona tu municipio</h1><select className="input mt-4" value={municipio} onChange={e=>setMunicipio(e.target.value)}><option value="">Municipio activo</option>{municipios.map(m=><option key={m.id} value={m.id}>{m.name}, {m.department}</option>)}</select><button className="btn mt-4" disabled={!municipio} onClick={start}>Comenzar encuesta</button></div>;
if(step==='encuesta'){const q=questions[idx];if(!q)return <div className="card">No hay preguntas activas para este municipio.</div>;return <div className="card max-w-2xl"><div className="mb-4 h-2 rounded bg-line"><div className="h-2 rounded bg-ink" style={{width:`${((idx+1)/questions.length)*100}%`}}/></div><p className="label">Pregunta {idx+1} de {questions.length}</p><h1 className="mt-2 text-2xl font-bold">{q?.question_text}</h1><div className="mt-6 grid gap-3">{(['a','b','c','d'] as const).map(k=><button key={k} className="rounded-xl border border-line p-4 text-left hover:bg-mist" onClick={()=>answer(q[`option_${k}_dimension`] as Dimension)}>{q[`option_${k}_text`]}</button>)}</div></div>}
const top=profile?[...DIMENSIONS].sort((a,b)=>profile[b]-profile[a]).slice(0,3):[];const ranked=cands.map(c=>({c,score:c.candidate_scores?.[0],m:c.candidate_scores?.[0]?matchCitizenToCandidate(profile!,c.candidate_scores[0] as any):null})).sort((a,b)=>(b.m?.match||0)-(a.m?.match||0));return <div className="grid gap-5"><div className="card"><h1 className="text-2xl font-bold">Tus 3 principales prioridades</h1><div className="mt-3 flex flex-wrap gap-2">{top.map(d=><span className="rounded-full bg-mist px-3 py-1" key={d}>{DIMENSION_LABELS[d]}: {profile![d]}/10</span>)}</div><p className="mt-4 text-sm text-slateblue">Esto no es una recomendación de voto. Es una comparación entre tus prioridades y los planes de gobierno cargados.</p></div>{ranked.map(({c,m})=><div className="card" key={c.id}><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold">{c.name}</h2><p className="text-slateblue">{c.party}</p></div><b className="text-3xl">{m?.match??0}%</b></div><p className="mt-3">{c.summary}</p><div className="mt-3 grid gap-2 md:grid-cols-2"><p><b>Coincidencias:</b> {m?.similarities.map(x=>DIMENSION_LABELS[x.dimension]).join(', ')}</p><p><b>Diferencias:</b> {m?.differences.map(x=>DIMENSION_LABELS[x.dimension]).join(', ')}</p></div></div>)}</div>}
